# ------------------------------------------------------------------------------
# This is an example configuration file for the tfb-status application.
#
# To create your own configuration file, start by copying this file and then
# modify whatever settings you want.  The structure of configuration files is
# defined by the following class:
#
#   src/main/java/tfb/status/bootstrap/ApplicationConfig.java
#
# Refer to that class for documentation about each of the available
# configuration settings.
#
# To run the tfb-status application with a custom configuration file, the first
# command-line argument for the application must be the path to that
# configuration file.
# ------------------------------------------------------------------------------

#http:
#  host: "0.0.0.0"
#  port: 80
#  keyStore:
#    path: src/test/resources/localhost.jks
#    password: password

#assets:
#  mode: FILE_SYSTEM

#mustache:
#  mode: FILE_SYSTEM

#fileStore:
#  root: managed_files

#email:
#  host: mail.techempower.com
#  port: 25
#  from: mhixson@techempower.com
#  to: mhixson@techempower.com

#runProgressMonitor:
#  environmentTimeoutSeconds: 21600
#  maxEnvironments: 5

#runCompleteMailer:
#  minSecondsBetweenEmails: 86400
